mouse/urls.py
from django.urls import path
from . import views

app_name = "mouse"
urlpatterns = [
    path("", views.index, name="index"),
    path("play.js", views.play, name="play"),
    path("get_record.js", views.get_record, name="get_record"),
    path("set_record.js", views.set_record, name="set_record"),
]

mouse/models.py
import uuid
from django.db import models


class Record(models.Model):
    """Model representing one recording."""

    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, help_text="Unique ID for recording."
    )
    time = models.FloatField(help_text="Time elapsed.")
    width = models.IntegerField(help_text="Width of screen.")
    height = models.IntegerField(help_text="Height of screen.")

    # User agent fields.
    is_bot = models.BooleanField(help_text="If user is a bot.")
    is_email_client = models.BooleanField(help_text="If user is an email client.")
    is_mobile = models.BooleanField(help_text="If user is mobile.")
    is_pc = models.BooleanField(help_text="If user is pc.")
    is_tablet = models.BooleanField(help_text="If user is tablet.")
    is_touch_capable = models.BooleanField(help_text="If user is touch capable.")
    ua_string = models.TextField(help_text="User agent description.")

    def __str__(self):
        """String for representing the Model object."""
        return "{} {} {},{} {}".format(
            self.id, self.time, self.width, self.height, self.ua_string
        )


class Frame(models.Model):
    """Model of frames recorded by musjs."""

    mode = models.CharField(max_length=1, help_text="Mode of mouse frame.")
    x = models.IntegerField(help_text="X-coordinate of mouse.")
    y = models.IntegerField(help_text="Y-coordinate of mouse.")
    record = models.ForeignKey(Record, on_delete=models.CASCADE)

    def __str__(self):
        """String for representing the Model object."""
        return "{} {} {}".format(self.mode, self.x, self.y)

mouse/views.py
import json
from .models import Frame, Record
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render


def index(request):
    """View function for home page of site."""

    # Count objects.
    frames = Frame.objects
    num_move = frames.filter(mode="m").count()
    num_click = frames.filter(mode="c").count()
    num_scroll = frames.filter(mode="s").count()
    records = Record.objects.all()

    # Render the HTML template index.html with the data in the context variable.
    return render(
        request,
        "mouse/index.html",
        context={
            "num_move": num_move,
            "num_click": num_click,
            "num_scroll": num_scroll,
            "records": records,
        },
    )


def play(request):
    """View function for playback page of recordings."""
    return render(request, "mouse/play.js", context={})


def set_record(request):
    """Store one mouse recording."""
    data = json.loads(next(iter(request.POST.dict())))
    user_agent = {}
    for attr in dir(request.user_agent):
        # Exclude private variables.
        if not "_" == attr[0]:
            # Exclude complex objects.
            if attr != "browser" and attr != "os" and attr != "device":
                user_agent[attr] = getattr(request.user_agent, attr)
    if data:
        window = data["window"]
        rec = Record(
            time=float(data["timeElapsed"]),
            width=int(window["width"]),
            height=int(window["height"]),
            **user_agent,
        )
        rec.save()
        for frame in data["frames"]:
            Frame(mode=frame[0], x=frame[1], y=frame[2], record=rec).save()

    # No Content, according to https://www.w3.org/TR/beacon/#sec-sendBeacon-method.
    return HttpResponse(status=204)


def get_record(request):
    """Return requested mouse recording."""
    request = request.GET
    if request and request["id"]:
        record = Record.objects.get(id=request["id"])
        return JsonResponse(
            {
                "success": True,
                "data": {
                    "frames": [
                        [frame.mode, frame.x, frame.y]
                        for frame in record.frame_set.all()
                    ],
                    "timeElapsed": record.time,
                    "window": {"width": record.width, "height": record.height},
                },
                "ua_string": record.ua_string,
            }
        )
    return JsonResponse({"success": False})

templates/mouse/index.html
{% extends "_base.html" %}
{% load static %}
{% block headerstatic %}
<script type="text/javascript" src="{% static 'js/mus.min.js' %}"></script>
<script type="text/javascript" src="{% url 'mouse:play' %}"></script>
{% endblock %}

{% block content %}
<div class="controls">
  <h1>Mus.js</h1>
  <p>The database has the following record counts:</p>
  <ul>
  <li><strong>Move:</strong> {{ num_move }}</li>
  <li><strong>Click:</strong> {{ num_click }}</li>
  <li><strong>Scroll:</strong> {{ num_scroll }}</li>
  </ul>

  <p>ua_string: <span id="ua_string"></span></p>
  <p>Status: <span id="status"></span></p>
  <p>Speed: <span id="speed">Normal</span></p>
  <br/>
  <button id="recording" onclick="toggleRecord();">Start recording</button>

  <form method="POST" id="playback_form">
    {% csrf_token %}
    <select id="record_id">
      {% for record in records %}<option value="{{ record.id }}">{{ record.id }}</option>{% endfor %}
    </select>
    <button type="submit" id="play">Play</button>
  </form>

  <br/>
  <button onclick="setSpeed(mus.speed.SLOW);">Slow</button>
  <button onclick="setSpeed(mus.speed.NORMAL);">Normal</button>
  <button onclick="setSpeed(mus.speed.FAST);">Fast</button>
  <br/>
  <button onclick="mus.release();">Release</button>
</div>

{% endblock %}