mouse/urls.py
from django.urls import path
from . import views

app_name = "mouse"
urlpatterns = [
    path("", views.index, name="index"),
    path("play.js", views.play, name="play"),
    path("get_record.js", views.get_record, name="get_record"),
    path("set_record.js", views.set_record, name="set_record"),
]

visualize/urls.py
from django.urls import path
from . import views

app_name = "visualize"
urlpatterns = [
    path("", views.index, name="index"),
    path("genHeatmap.js", views.gen_heatmap_js, name="genHeatmap"),
    path("genTime.js", views.gen_time_js, name="genTime"),
    path("genLoc.js", views.gen_loc_js, name="genLoc"),
    path("map.js", views.map_js, name="map"),
    path("slider.js", views.slider_js, name="slider"),
    path("ui.js", views.ui_js, name="ui"),
    path("ui_mobile.js", views.ui_mobile_js, name="ui_mobile"),
    path("chart.js", views.chart_js, name="chart"),
    path("stats.js", views.stats_js, name="stats"),
    path("genChart.js", views.gen_chart_js, name="genChart"),
    path("genCost.js", views.get_cost_data_js, name="cost"),
]

templates/mobile/index.html
{% extends "_base.html" %}
{% load static %}
{% block headerstatic %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/9.9.0/css/bootstrap-slider.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">


<script async src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/9.9.0/bootstrap-slider.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.13.0/xlsx.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.8/FileSaver.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/TableExport/5.0.2/js/tableexport.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/TableExport/5.0.2/css/tableexport.min.css">

<script src="https://cdnjs.cloudflare.com/ajax/libs/PapaParse/4.5.0/papaparse.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.30.6/js/jquery.tablesorter.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.30.6/js/extras/jquery.tablesorter.pager.min.js"></script>

<link rel="stylesheet" href="{% static 'mobile/ui.css' %}">
<link rel="stylesheet" href="{% static 'css/map.css' %}">
<link rel="stylesheet" href="{% static 'css/button.css' %}">
<script type="text/javascript" src="{% static 'js/control.js' %}" ></script>
<script type="text/javascript" src="{% static 'js/itinerary.js' %}" ></script>
<script type="text/javascript" src="{% static 'mobile/table.js' %}" ></script>
<script type="text/javascript" src="{% static 'js/mus.min.js' %}" ></script>
<script type="text/javascript" src="{% url 'visualize:chart' %}" ></script>
<script type="text/javascript" src="{% url 'visualize:map' %}" ></script>
<script type="text/javascript" src="{% url 'visualize:ui_mobile' %}" ></script>
<script defer type="text/javascript" src="{% url 'visualize:stats' %}" ></script>
<script defer type="text/javascript" src="{% url 'visualize:slider' %}" ></script>
<script defer src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLEMAPS_SECRET_KEY }}&libraries=visualization,places&callback=initMap&region=SG"></script>
{% endblock %}
{% block content %}
<!--Error Message-->
<div id="container-error">
  {% if error_message %}
  <p><strong>{{ error_message }}</strong></p>
  {% endif %}
</div>


<div id= "map-all">

    <!-- Google maps. -->
    <div id="map"></div>
    <!-- Show nearby-->
    <div id="container-button"onclick = "showNearby()">
        <a href="#" id="here-button">
            <i class="fas fa-map-marker-alt"></i>
        </a>
    </div>


    <!-- Controls (Top left) -->
    <div id="menuToggle">
        <input type="checkbox" />

        <!--hamburger-->
        <span></span>
        <span></span>
        <span></span>

        <ul id="container-controls"><!--Switch-->
            <div class = "container-bg"></div>

            <div class = "container-controls-headers"> FUNCTION CONTROLS </div>
            <div id = "controls-container-functions">
            <table>
                <tr>
                    <td>
                        Toggle Now/Later
                    </td>
                    <td>
                        <div class="switch switch--horizontal switch--expanding-inner">
                            <input id="radio-i" type="radio" name="fifth-switch" checked="checked" onchange="toggleNowLater()"/>
                            <label for="radio-i">Now</label>
                            <input id="radio-j" type="radio" name="fifth-switch" onchange="toggleNowLater()"/>
                            <label for="radio-j">Later</label>
                            <span class="toggle-outside"><span class="toggle-inside"></span></span>
                        </div>
                    </td>
                </tr>
            </table>
                <button class="controls-functions" onclick="unsetLocation()">Reset location</button>
            </div>


            <div class = "container-controls-headers"> DISPLAY CONTROLS</div>
            <table>
                <tr>
                    <td>
                        Toggle UI
                    </td>
                    <td>
                        <div class="switch switch--horizontal switch--expanding-inner">
                            <input id="radio-i" type="radio" name="fifth-switch" checked="checked" onchange="toggleUi()"/>
                            <label for="radio-i">On</label>
                            <input id="radio-j" type="radio" name="fifth-switch" onchange="toggleUi()"/>
                            <label for="radio-j">Off</label>
                            <span class="toggle-outside"><span class="toggle-inside"></span></span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        Toggle Heatmap
                    </td>
                    <td>
                        <div class="switch switch--horizontal switch--expanding-inner">
                            <input id="radio-i" type="radio" name="fifth-switch" checked="checked" onchange="toggleHeatmap()"/>
                            <label for="radio-i">On</label>
                            <input id="radio-j" type="radio" name="fifth-switch" onchange="toggleHeatmap()"/>
                            <label for="radio-j">Off</label>
                            <span class="toggle-outside"><span class="toggle-inside"></span></span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        Toggle Gradient
                    </td>
                    <td>
                        <div class="switch switch--horizontal switch--expanding-inner">
                            <input id="radio-i" type="radio" name="fifth-switch" checked="checked" onchange="changeGradient()"/>
                            <label for="radio-i">Green</label>
                            <input id="radio-j" type="radio" name="fifth-switch" onchange="changeGradient()"/>
                            <label for="radio-j">Blue</label>
                            <span class="toggle-outside"><span class="toggle-inside"></span></span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        Change Radius
                    </td>
                    <td>
                        <div class="switch switch--horizontal switch--expanding-inner">
                            <input id="radio-i" type="radio" name="fifth-switch" checked="checked" onchange="changeRadius()"/>
                            <label for="radio-i">Small</label>
                            <input id="radio-j" type="radio" name="fifth-switch" onchange="changeRadius()"/>
                            <label for="radio-j">Big</label>
                            <span class="toggle-outside"><span class="toggle-inside"></span></span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        Change Opacity
                    </td>
                    <td>
                        <div class="switch switch--horizontal switch--expanding-inner">
                            <input id="radio-i" type="radio" name="fifth-switch" checked="checked" onchange="changeOpacity()"/>
                            <label for="radio-i">Heavy</label>
                            <input id="radio-j" type="radio" name="fifth-switch" onchange="changeOpacity()"/>
                            <label for="radio-j">Light</label>
                            <span class="toggle-outside"><span class="toggle-inside"></span></span>
                        </div>
                    </td>
                </tr>
            </table>


        </ul>
    </div>
    <div id="description-controls">
        CONTROL PANEL

    </div>


    <!-- UI -->
    <div id="container-ui">



    <!--Sliders-->
    <div class="container-slider bottom-display" id="container-slider-now">
        <div class = "container-bg-container">
            <div class = "container-bg"></div>
        </div>
        <div class = "container-slider-inner">
            <div> VISUALIZATION SLIDERS (NOW)</div>
            <div> Slide across time </div>
            <input type="range" id="genTime" data-slider-id="genTimeSlider" type="text" data-slider-min="0" data-slider-max="5" data-slider-step="1" data-slider-value="0"><br>
            <input id="pac-input-slider" class="controls td-height pac-input-slider" type="text" placeholder="Search Google Maps">
        </div>
    </div>

    <div class = "container-slider bottom-display" id="container-slider-later">
        <div class = "container-bg-container">
            <div class = "container-bg"></div>
        </div>
        <div class = "container-slider-inner">
            <div> VISUALIZATION SLIDERS (LATER)</div>
            <div> Slide across heatmap </div>
            <input type="range" id="genHeatmap" data-slider-id="genHeatmapSlider" type="text" data-slider-min="0" data-slider-max="1440" data-slider-step="5" data-slider-value="0"><br>
            <div> Slide across heatmap intensity</div>
            <input type="range" id="genHeatmapIntensity" data-slider-id="genHeatmapIntensitySlider" type="text" data-slider-min="1" data-slider-max="10" data-slider-step="1" data-slider-value="0"><br>
            <div>Slide location radius</div>
            <input type="range" id="genLocationRadius" data-slider-id="genLocationRadiusSlider" type="text" data-slider-min="50" data-slider-max="5000" data-slider-step="10" data-slider-value="500"><br>
            <div class='input-group date' id='datetimepicker'>
                <input type='text' class="form-control"/>
                <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
            <input id="pac-input-slider" class="controls td-height pac-input-slider" type="text" placeholder="Search Google Maps">
        </div>

    </div>



    <!-- Itinerary table-->
    <div id = "container-itinerary" class = "bottom-display">
        <div id = "container-itinerary-inner">
            <div class = "container-bg-container">
                <div class = "container-bg"></div>
            </div>
            <table id="itineraryTable" class="tablesorter" cellspacing="1">

                <thead>
                    <tr>
                        <th>Pickup Location</th>
                        <th>Pickup Time</th>
                        <th>Arrival Location</th>
                        <th>Arrival Time</th>
                    </tr>
                </thead>
                <tbody></tbody>
                </caption>
            </table>


            <div id="pager" class="pager">
                <form>
                    <img src="{% static 'img/first.png' %}" class="first"/>
                    <img src="{% static 'img/prev.png' %}" class="prev"/>
                    <input type="text" class="pagedisplay"/>
                    <img src="{% static 'img/next.png' %}" class="next"/>
                    <img src="{% static 'img/last.png' %}" class="last"/>
                    <select class="pagesize">
                        <option selected="selected" value="1">1</option>
                        <option value="10">10</option>
                        <option value="10">15</option>
                        <option value="20">20</option>
                    </select>
                </form>
            </div>
        </div>
    </div>
    <!--Local statistics(Right)-->
    <div id = "container-stats" class = "bottom-display">
        <div class = "container-bg"></div>
        <table id = "stats-table">
            <tr>
                <th> Statistics of taxis within 500m:</th>
            <tr>
                <td> Number of taxis:</td>
                <td id="num"> "-" </td>
            </tr>
            <tr>
                <td>Average distance:</td>
                <td id="average_dist"> "-"</td>
            </tr>
        </table>

    </div>





    <!-- End of UI -->

    <div class ="mobile-bottom-bar">
        <a href="#" class="footer-link">
            <i class="fas fa-sliders-h"></i><span onclick="toggleSliders()"class='footer-text'>Sliders</span>
        </a>
        <a href="#" class="footer-link">
            <i class="fas fa-calculator"></i> <span onclick = "toggleStats()"class='footer-text'>Statistics</span>
        </a>
    </div>
    <div id = "bottom-display">

    </div>
</div>
</div>
<script src="https://d3js.org/d3.v4.min.js"></script>



{% endblock %}