mouse/urls.py
from django.urls import path
from . import views

app_name = "mouse"
urlpatterns = [
    path("", views.index, name="index"),
    path("play.js", views.play, name="play"),
    path("get_record.js", views.get_record, name="get_record"),
    path("set_record.js", views.set_record, name="set_record"),
]

visualize/urls.py
from django.urls import path
from . import views

app_name = "visualize"
urlpatterns = [
    path("", views.index, name="index"),
    path("genHeatmap.js", views.gen_heatmap_js, name="genHeatmap"),
    path("genTime.js", views.gen_time_js, name="genTime"),
    path("genLoc.js", views.gen_loc_js, name="genLoc"),
    path("map.js", views.map_js, name="map"),
    path("slider.js", views.slider_js, name="slider"),
    path("ui.js", views.ui_js, name="ui"),
    path("ui_mobile.js", views.ui_mobile_js, name="ui_mobile"),
    path("chart.js", views.chart_js, name="chart"),
    path("stats.js", views.stats_js, name="stats"),
    path("genChart.js", views.gen_chart_js, name="genChart"),
    path("genCost.js", views.get_cost_data_js, name="cost"),
]

visualize/views.py
import datetime
import pytz

from background_task.models import Task
from daemons.models import Coordinate, Timestamp, Location
from daemons.views import (
    get_coordinates_time,
    get_coordinates_location,
    get_heatmap_time,
    serialize_coordinates,
    get_best_road,
    get_chart_data,
)
from django.shortcuts import render
from django.utils import timezone
from django.conf import settings
from django.http import JsonResponse
from visualize.heatmap_slider import HeatmapSlider
from daemons.farecalculator import calculateCost


def index(request):
    """View function for home page of site."""
    context = {
        "GOOGLEMAPS_SECRET_KEY": settings.GOOGLEMAPS_SECRET_KEY,
        "error_message": "Note: Location may not be accurate. We store your mouse data.",
    }
    index = (
        "mobile/index.html" if request.user_agent.is_mobile else "visualize/index.html"
    )

    # Else: render with normal context.
    return render(request, index, context)


def gen_heatmap_js(request):
    """Return Json of intensity, coords, and timestamp of heat tile."""
    heattiles, timestamp = get_heatmap_time(request)
    if timestamp == None:
        return JsonResponse({"heattiles": heattiles, "timestamp": None})
    return JsonResponse({"heattiles": heattiles, "timestamp": timestamp.date_time})


def gen_time_js(request):
    """Return Json of serialized list of coordinates according to time."""
    return JsonResponse(
        {"coordinates": serialize_coordinates(get_coordinates_time(request))}
    )


def gen_loc_js(request):
    """Return Json of serialized list of coordinates, average distance away, and number of taxis according to the location"""
    coords, total_dist, number, best_road_name, lat, lng, path_geom, path_instructions, path_time, path_dist = get_coordinates_location(
        request
    )

    return JsonResponse(
        {
            "coordinates": serialize_coordinates(coords),
            "total_dist": total_dist,
            "number": number,
            "best_road": best_road_name,
            "best_road_coords": {"lat": lat, "lng": lng},
            "path_geom": path_geom,
            "path_instructions": path_instructions,
            "path_time": path_time,
            "path_dist": path_dist,
        }
    )


if settings.VISUALIZE_LOCATIONS:

    def map_js(request):
        """Render Javascript file with coordinates of Locations."""
        return render(
            request,
            "visualize/map.js",
            {
                "coordinates": Location.objects.exclude(
                    lat=1.352083, lng=103.819836
                ).all()
            },
        )


else:

    def map_js(request):
        """Render Javascript file with list of coordinates in context."""
        return render(
            request,
            "visualize/map.js",
            {
                "coordinates": get_coordinates_time(request),
                "mobile": request.user_agent.is_mobile,
            },
        )


def slider_js(request):
    """Render Javascript file with list of coordinates in context."""
    return render(request, "visualize/slider.js", {"SLIDE_EVENT": settings.SLIDE_EVENT})


def chart_js(request):
    """Render Javascript file."""
    return render(request, "visualize/chart.js")


def ui_base_js(request, app):
    """Render Javascript file."""
    context = {"GOOGLEMAPS_SECRET_KEY": settings.GOOGLEMAPS_SECRET_KEY}
    return render(request, app + "/ui.js", context)


def ui_mobile_js(request):
    return ui_base_js(request, "mobile")


def ui_js(request):
    return ui_base_js(request, "visualize")


def stats_js(request):
    """Render Javascript file."""
    return render(
        request, "visualize/stats.js", {"mobile": request.user_agent.is_mobile}
    )


def gen_chart_js(request):
    day_stats, chart_title = get_chart_data(request)
    return JsonResponse({"day_stats": day_stats, "chart_title": chart_title})


def get_cost_data_js(request):
    cost = calculateCost(request.GET.get("distance"), request.GET.get("time"))
    return JsonResponse({"cost": cost})

templates/visualize/index.html
{% extends "_base.html" %}
{% load static %}
{% block headerstatic %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/9.9.0/css/bootstrap-slider.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.13.0/xlsx.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.8/FileSaver.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/TableExport/5.0.2/js/tableexport.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/TableExport/5.0.2/css/tableexport.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/9.9.0/bootstrap-slider.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.30.6/js/jquery.tablesorter.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.30.6/js/extras/jquery.tablesorter.pager.min.js"></script>

<script async src="https://cdnjs.cloudflare.com/ajax/libs/PapaParse/4.5.0/papaparse.min.js"></script>
<link rel="stylesheet" href="{% static 'css/ui.css' %}">
<link rel="stylesheet" href="{% static 'css/map.css' %}">
<link rel="stylesheet" href="{% static 'css/button.css' %}">
<script type="text/javascript" src="{% static 'js/control.js' %}" ></script>
<script type="text/javascript" src="{% static 'js/itinerary.js' %}" ></script>
<script type="text/javascript" src="{% static 'js/table.js' %}" ></script>
<script type="text/javascript" src="{% static 'js/mus.min.js' %}" ></script>
<script type="text/javascript" src="{% url 'visualize:chart' %}" ></script>
<script type="text/javascript" src="{% url 'visualize:map' %}" ></script>
<script type="text/javascript" src="{% url 'visualize:ui' %}" ></script>
<script defer type="text/javascript" src="{% url 'visualize:stats' %}" ></script>
<script defer type="text/javascript" src="{% url 'visualize:slider' %}" ></script>
<script defer src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLEMAPS_SECRET_KEY }}&libraries=visualization,places&callback=initMap&region=SG"></script>
{% endblock %}
{% block content %}

<!--Error Message-->
<div id="container-error">
  {% if error_message %}
  <button onclick="document.getElementById('container-error').style.display='none';" type="button" class="close" aria-label="Close" style="float:left;display:inline-block"><span aria-hidden="true">&times;</span></button>
  <p style="display:inline-block;padding-left:10px"><strong>{{ error_message }}</strong></p>
  {% endif %}
</div>
<div id= "map-all">



    <!-- Google maps. -->
    <div id="map"></div>


    <!-- Controls (Top left) -->
    <div id="menuToggle">
        <input type="checkbox" checked="checked"/>

        <!--hamburger-->
        <span></span>
        <span></span>
        <span></span>

        <ul id="container-controls"><!--Switch-->
            <div class = "container-bg"></div>

            <div class = "container-controls-headers"> FUNCTION CONTROLS </div>
            <div id = "controls-container-functions">
            <table>
                <tr>
                    <td>
                        Toggle Now/Later
                    </td>
                    <td>
                        <div class="switch switch--horizontal switch--expanding-inner">
                            <input id="radio-i" type="radio" name="fifth-switch" checked="checked" onchange="toggleNowLater()"/>
                            <label for="radio-i">Now</label>
                            <input id="radio-j" type="radio" name="fifth-switch" onchange="toggleNowLater()"/>
                            <label for="radio-j">Later</label>
                            <span class="toggle-outside"><span class="toggle-inside"></span></span>
                        </div>
                    </td>
                </tr>
            </table>
                <button class="controls-functions" onclick="showNearby()">Show near-by taxis</button>
                <button class="controls-functions" onclick="unsetLocation()">Reset location</button>
            </div>


            <div class = "container-controls-headers"> DISPLAY CONTROLS</div>
            <table>
                <tr>
                    <td>
                        Toggle UI
                    </td>
                    <td>
                        <div class="switch switch--horizontal switch--expanding-inner">
                            <input id="radio-i" type="radio" name="fifth-switch" checked="checked" onchange="toggleUi()"/>
                            <label for="radio-i">On</label>
                            <input id="radio-j" type="radio" name="fifth-switch" onchange="toggleUi()"/>
                            <label for="radio-j">Off</label>
                            <span class="toggle-outside"><span class="toggle-inside"></span></span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        Toggle Heatmap
                    </td>
                    <td>
                        <div class="switch switch--horizontal switch--expanding-inner">
                            <input id="radio-i" type="radio" name="fifth-switch" checked="checked" onchange="toggleHeatmap()"/>
                            <label for="radio-i">On</label>
                            <input id="radio-j" type="radio" name="fifth-switch" onchange="toggleHeatmap()"/>
                            <label for="radio-j">Off</label>
                            <span class="toggle-outside"><span class="toggle-inside"></span></span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        Toggle Gradient
                    </td>
                    <td>
                        <div class="switch switch--horizontal switch--expanding-inner">
                            <input id="radio-i" type="radio" name="fifth-switch" checked="checked" onchange="changeGradient()"/>
                            <label for="radio-i">Green</label>
                            <input id="radio-j" type="radio" name="fifth-switch" onchange="changeGradient()"/>
                            <label for="radio-j">Blue</label>
                            <span class="toggle-outside"><span class="toggle-inside"></span></span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        Change Radius
                    </td>
                    <td>
                        <div class="switch switch--horizontal switch--expanding-inner">
                            <input id="radio-i" type="radio" name="fifth-switch" checked="checked" onchange="changeRadius()"/>
                            <label for="radio-i">Small</label>
                            <input id="radio-j" type="radio" name="fifth-switch" onchange="changeRadius()"/>
                            <label for="radio-j">Big</label>
                            <span class="toggle-outside"><span class="toggle-inside"></span></span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        Change Opacity
                    </td>
                    <td>
                        <div class="switch switch--horizontal switch--expanding-inner">
                            <input id="radio-i" type="radio" name="fifth-switch" checked="checked" onchange="changeOpacity()"/>
                            <label for="radio-i">Heavy</label>
                            <input id="radio-j" type="radio" name="fifth-switch" onchange="changeOpacity()"/>
                            <label for="radio-j">Light</label>
                            <span class="toggle-outside"><span class="toggle-inside"></span></span>
                        </div>
                    </td>
                </tr>
            </table>


        </ul>
    </div>
    <div id="description-controls">
        CONTROL PANEL

    </div>


    <!-- UI -->
    <div id="container-ui">

    <!--Sliders (top right)-->
    <div class="container-slider" id="container-slider-now">
        <div class = "container-bg-container">
            <div class = "container-bg"></div>
        </div>
        <div class = "container-slider-inner">
            <div> VISUALIZATION SLIDERS (NOW)</div>
            <div> Slide across time </div>
            <input type="range" id="genTime" data-slider-id="genTimeSlider" type="text" data-slider-min="0" data-slider-max="5" data-slider-step="1" data-slider-value="0"><br>
            <input id="pac-input-slider" class="controls td-height pac-input-slider" type="text" placeholder="Search Google Maps">
        </div>
    </div>

    <div class = "container-slider" id="container-slider-later">
        <div class = "container-bg-container">
            <div class = "container-bg"></div>
        </div>
        <div class = "container-slider-inner">
            <div> VISUALIZATION SLIDERS (LATER)</div>
            <div> Slide across predicted future </div>
            <input type="range" id="genHeatmap" data-slider-id="genHeatmapSlider" type="text" data-slider-min="0" data-slider-max="1440" data-slider-step="1" data-slider-value="0"><br>
            <div> Slide across heatmap intensity</div>
            <input type="range" id="genHeatmapIntensity" data-slider-id="genHeatmapIntensitySlider" type="text" data-slider-min="1" data-slider-max="10" data-slider-step="1" data-slider-value="0"><br>
            <div>Slide location radius</div>
            <input type="range" id="genLocationRadius" data-slider-id="genLocationRadiusSlider" type="text" data-slider-min="50" data-slider-max="5000" data-slider-step="10" data-slider-value="500"><br>
            <div class='input-group date' id='datetimepicker'>
                <input type='text' class="form-control"/>
                <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
            <input id="pac-input-slider" class="controls td-height pac-input-slider" type="text" placeholder="Search Google Maps">
        </div>

    </div>



    <!-- Itinerary table (top left)-->
    <div id = "container-itinerary">
        <div id="arrow-holder">
        <div class="arrow" id = "slider"></div>
        </div>
        <div id = "container-itinerary-inner">
            <div class = "container-bg-container">
                <div class = "container-bg"></div>
            </div>
            <input type="button" id="addRow" value="Add row">
            <table id="itineraryTable" class="tablesorter" cellspacing="1">


                <thead>
                    <tr>
                        <th>Pickup Location</th>
                        <th>Pickup Time</th>
                        <th>Arrival Location</th>
                        <th>Arrival Time</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
            <caption id="tableimport-caption" class = "bottom">
            <label for="importFromCsv" class="btn btn-default csv">Import</label>
            <input id="importFromCsv" type="file"/>
            </caption>


            <div id="pager" class="pager">
                <form>
                    <img src="{% static 'img/first.png' %}" class="first"/>
                    <img src="{% static 'img/prev.png' %}" class="prev"/>
                    <input type="text" class="pagedisplay"/>
                    <img src="{% static 'img/next.png' %}" class="next"/>
                    <img src="{% static 'img/last.png' %}" class="last"/>
                    <select class="pagesize">
                        <option selected="selected" value="5">5</option>
                        <option value="10">10</option>
                        <option value="10">15</option>
                        <option value="20">20</option>
                    </select>
                </form>
            </div>
        </div>
    </div>

    <!--SVG for charts -->
    <div id="container-chart" >
        <svg class="chart"></svg>
        <div id="chart-title">Title</div>
    </div>

    <!--Local statistics(Right)-->
    <div id = "container-stats">
        <button id="remove-stats" onclick="disappearStats()"type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <div class = "container-bg"></div>
        <table id = "stats-table">
            <tr>
                <th> Statistics of taxis within 500m:</th>
            <tr>
                <td> Number of taxis:</td>
                <td id="num"> "-" </td>
            </tr>
            <tr>
                <td>Average distance:</td>
                <td id="average_dist"> "-"</td>
            </tr>
        </table>

    </div>

    <!-- End of UI -->
</div>
</div>

<script src="https://d3js.org/d3.v4.min.js"></script>

{% endblock %}